import "./globals.css";
import { ReactNode } from "react";
import Footer from "@/components/Footer";
import { poppins } from "@/fonts";
import { MainNavBar } from "@/components/mainNavBar";

// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <MainNavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
